--- #YAML:1.0
name:                file2ftp
version:             0.0101
abstract:            upload files to FTP server based on preset config
license:             ~
author:              
    - Zoffix Znet <zoffix@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Net::FTP:                      2.77
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
